---
# MongoDB 副本集主机清单

all:
  children:
    mongodb:
      hosts:
        mongodb-1:
          ansible_host: 172.27.0.10
          ansible_user: root
        mongodb-2:
          ansible_host: 172.27.0.11
          ansible_user: root
        mongodb-3:
          ansible_host: 172.27.0.12
          ansible_user: root

    mongodb_cluster:
      hosts:
        mongodb-1:
        mongodb-2:
        mongodb-3: