---
- name: 测试部署
  hosts: localhost
  connection: local
  gather_facts: no
  
  tasks:
    - name: 测试 Jenkins WAR 包是否存在
      ansible.builtin.stat:
        path: /opt/ansible/downloads/jenkins-2.452.1.war
      register: jenkins_war
      
    - name: 显示结果
      ansible.builtin.debug:
        msg: "Jenkins WAR 包存在: {{ jenkins_war.stat.exists }}"
        
    - name: 测试容器是否运行
      ansible.builtin.command: docker ps --filter "name=jenkins-server" --format "{{ '{{' }}.Names{{ '}}' }}"
      register: container_status
      changed_when: false
      
    - name: 显示容器状态
      ansible.builtin.debug:
        msg: "Jenkins 容器状态: {{ container_status.stdout }}"
