---
# SonarQube 代码质量分析平台主机清单

all:
  children:
    sonarqube:
      hosts:
        sonarqube-1:
          ansible_host: 172.28.0.30
          ansible_user: root
          ansible_become: false

    postgresql:
      hosts:
        postgresql-1:
          ansible_host: 172.28.0.31
          ansible_user: root
          ansible_become: false