version: '3.8'

# Docker 测试环境 - 模拟 VictoriaMetrics 监控栈主机

services:
  # vmstorage 节点
  vmstorage-1:
    image: rockylinux:9
    container_name: vmstorage-1
    hostname: vmstorage-1
    privileged: true
    networks:
      vm-net:
        ipv4_address: 172.22.0.10
    command: tail -f /dev/null

  vmstorage-2:
    image: rockylinux:9
    container_name: vmstorage-2
    hostname: vmstorage-2
    privileged: true
    networks:
      vm-net:
        ipv4_address: 172.22.0.11
    command: tail -f /dev/null

  vmstorage-3:
    image: rockylinux:9
    container_name: vmstorage-3
    hostname: vmstorage-3
    privileged: true
    networks:
      vm-net:
        ipv4_address: 172.22.0.12
    command: tail -f /dev/null

  # vminsert 节点
  vminsert-1:
    image: rockylinux:9
    container_name: vminsert-1
    hostname: vminsert-1
    privileged: true
    networks:
      vm-net:
        ipv4_address: 172.22.0.13
    command: tail -f /dev/null

  vminsert-2:
    image: rockylinux:9
    container_name: vminsert-2
    hostname: vminsert-2
    privileged: true
    networks:
      vm-net:
        ipv4_address: 172.22.0.14
    command: tail -f /dev/null

  vminsert-3:
    image: rockylinux:9
    container_name: vminsert-3
    hostname: vminsert-3
    privileged: true
    networks:
      vm-net:
        ipv4_address: 172.22.0.15
    command: tail -f /dev/null

  # vmselect 节点
  vmselect-1:
    image: rockylinux:9
    container_name: vmselect-1
    hostname: vmselect-1
    privileged: true
    networks:
      vm-net:
        ipv4_address: 172.22.0.16
    command: tail -f /dev/null

  vmselect-2:
    image: rockylinux:9
    container_name: vmselect-2
    hostname: vmselect-2
    privileged: true
    networks:
      vm-net:
        ipv4_address: 172.22.0.17
    command: tail -f /dev/null

  vmselect-3:
    image: rockylinux:9
    container_name: vmselect-3
    hostname: vmselect-3
    privileged: true
    networks:
      vm-net:
        ipv4_address: 172.22.0.18
    command: tail -f /dev/null

  # vmauth 节点 (认证和路由，映射端口)
  vmauth-1:
    image: rockylinux:9
    container_name: vmauth-1
    hostname: vmauth-1
    privileged: true
    networks:
      vm-net:
        ipv4_address: 172.22.0.19
    command: tail -f /dev/null
    ports:
      - "8427:8427"

  # vmalert 节点 (告警规则，映射端口)
  vmalert-1:
    image: rockylinux:9
    container_name: vmalert-1
    hostname: vmalert-1
    privileged: true
    networks:
      vm-net:
        ipv4_address: 172.22.0.20
    command: tail -f /dev/null
    ports:
      - "8880:8880"

  # vmagent 节点 (采集指标，映射端口)
  vmagent-1:
    image: rockylinux:9
    container_name: vmagent-1
    hostname: vmagent-1
    privileged: true
    networks:
      vm-net:
        ipv4_address: 172.22.0.21
    command: tail -f /dev/null
    ports:
      - "8429:8429"

  # alertmanager 节点 (告警管理，映射端口)
  alertmanager-1:
    image: rockylinux:9
    container_name: alertmanager-1
    hostname: alertmanager-1
    privileged: true
    networks:
      vm-net:
        ipv4_address: 172.22.0.22
    command: tail -f /dev/null
    ports:
      - "9095:9093"

  # grafana 节点 (可视化，映射端口)
  grafana-1:
    image: rockylinux:9
    container_name: grafana-1
    hostname: grafana-1
    privileged: true
    networks:
      vm-net:
        ipv4_address: 172.22.0.23
    command: tail -f /dev/null
    ports:
      - "3001:3000"

networks:
  vm-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1