version: '3.8'

# Docker Compose 配置用于创建 Ansible 测试主机
# 使用 Rocky Linux 9 轻量级镜像作为测试环境

services:
  # vmselect-1: 查询节点 1
  vmselect-1:
    image: rockylinux:9
    container_name: vmselect-1
    hostname: vmselect-1
    command: tail -f /dev/null
    networks:
      vmnet:
        ipv4_address: 172.20.0.10
    volumes:
      - vmselect-1-data:/var/lib/victoriametrics

  # vmselect-2: 查询节点 2
  vmselect-2:
    image: rockylinux:9
    container_name: vmselect-2
    hostname: vmselect-2
    command: tail -f /dev/null
    networks:
      vmnet:
        ipv4_address: 172.20.0.11
    volumes:
      - vmselect-2-data:/var/lib/victoriametrics

  # vminsert-1: 写入节点 1
  vminsert-1:
    image: rockylinux:9
    container_name: vminsert-1
    hostname: vminsert-1
    command: tail -f /dev/null
    networks:
      vmnet:
        ipv4_address: 172.20.0.12
    volumes:
      - vminsert-1-data:/var/lib/victoriametrics

  # vminsert-2: 写入节点 2
  vminsert-2:
    image: rockylinux:9
    container_name: vminsert-2
    hostname: vminsert-2
    command: tail -f /dev/null
    networks:
      vmnet:
        ipv4_address: 172.20.0.13
    volumes:
      - vminsert-2-data:/var/lib/victoriametrics

  # vmstorage-1: 存储节点 1
  vmstorage-1:
    image: rockylinux:9
    container_name: vmstorage-1
    hostname: vmstorage-1
    command: tail -f /dev/null
    networks:
      vmnet:
        ipv4_address: 172.20.0.14
    volumes:
      - vmstorage-1-data:/var/lib/victoriametrics

  # vmstorage-2: 存储节点 2
  vmstorage-2:
    image: rockylinux:9
    container_name: vmstorage-2
    hostname: vmstorage-2
    command: tail -f /dev/null
    networks:
      vmnet:
        ipv4_address: 172.20.0.15
    volumes:
      - vmstorage-2-data:/var/lib/victoriametrics

  # vmstorage-3: 存储节点 3
  vmstorage-3:
    image: rockylinux:9
    container_name: vmstorage-3
    hostname: vmstorage-3
    command: tail -f /dev/null
    networks:
      vmnet:
        ipv4_address: 172.20.0.16
    volumes:
      - vmstorage-3-data:/var/lib/victoriametrics

networks:
  vmnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

volumes:
  vmselect-1-data:
  vmselect-2-data:
  vminsert-1-data:
  vminsert-2-data:
  vmstorage-1-data:
  vmstorage-2-data:
  vmstorage-3-data: