---
# RabbitMQ 集群 + HA + Keepalived 测试主机清单（Docker 连接）

all:
  children:
    rabbitmq:
      hosts:
        rabbitmq-1:
          ansible_host: rabbitmq-1
          ansible_connection: community.docker.docker
          ansible_user: root
          rabbitmq_node_type: master
          rabbitmq_nodename: rabbit@rabbitmq-1
        rabbitmq-2:
          ansible_host: rabbitmq-2
          ansible_connection: community.docker.docker
          ansible_user: root
          rabbitmq_node_type: slave
          rabbitmq_nodename: rabbit@rabbitmq-2
        rabbitmq-3:
          ansible_host: rabbitmq-3
          ansible_connection: community.docker.docker
          ansible_user: root
          rabbitmq_node_type: slave
          rabbitmq_nodename: rabbit@rabbitmq-3

    keepalived:
      hosts:
        keepalived-1:
          ansible_host: keepalived-1
          ansible_connection: community.docker.docker
          ansible_user: root
          keepalived_state: MASTER
          keepalived_priority: 100
          keepalived_vip: 172.29.0.100
        keepalived-2:
          ansible_host: keepalived-2
          ansible_connection: community.docker.docker
          ansible_user: root
          keepalived_state: BACKUP
          keepalived_priority: 90
          keepalived_vip: 172.29.0.100

    haproxy:
      hosts:
        keepalived-1:
          ansible_host: keepalived-1
          ansible_connection: community.docker.docker
          ansible_user: root
        keepalived-2:
          ansible_host: keepalived-2
          ansible_connection: community.docker.docker
          ansible_user: root