version: '3.8'

# Docker 测试环境 - MySQL Group Replication + Router

services:
  # MySQL MGR 节点 1
  mysql-mgr-1:
    image: rockylinux-ansible-test:9
    container_name: mysql-mgr-1
    hostname: mysql-mgr-1
    privileged: true
    networks:
      mysql-mgr-net:
        ipv4_address: 172.25.0.10
    command: tail -f /dev/null

  # MySQL MGR 节点 2
  mysql-mgr-2:
    image: rockylinux-ansible-test:9
    container_name: mysql-mgr-2
    hostname: mysql-mgr-2
    privileged: true
    networks:
      mysql-mgr-net:
        ipv4_address: 172.25.0.11
    command: tail -f /dev/null

  # MySQL MGR 节点 3
  mysql-mgr-3:
    image: rockylinux-ansible-test:9
    container_name: mysql-mgr-3
    hostname: mysql-mgr-3
    privileged: true
    networks:
      mysql-mgr-net:
        ipv4_address: 172.25.0.12
    command: tail -f /dev/null

  # MySQL Router
  router-1:
    image: rockylinux-ansible-test:9
    container_name: router-1
    hostname: router-1
    privileged: true
    networks:
      mysql-mgr-net:
        ipv4_address: 172.25.0.13
    command: tail -f /dev/null
    ports:
      - "6446:6446"
      - "6447:6447"
      - "6448:6448"

networks:
  mysql-mgr-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.27.0.0/16
          gateway: 172.27.0.1