version: '3.8'

# Docker Compose 配置用于创建 RabbitMQ 集群测试主机
# 使用 Rocky Linux 9 镜像作为测试环境

services:
  # RabbitMQ 节点 1
  rabbitmq-1:
    image: rockylinux:9
    container_name: rabbitmq-1
    hostname: rabbitmq-1
    command: tail -f /dev/null
    networks:
      rabbitmqnet:
        ipv4_address: 172.29.0.10
    volumes:
      - rabbitmq-1-data:/var/lib/rabbitmq
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  # RabbitMQ 节点 2
  rabbitmq-2:
    image: rockylinux:9
    container_name: rabbitmq-2
    hostname: rabbitmq-2
    command: tail -f /dev/null
    networks:
      rabbitmqnet:
        ipv4_address: 172.29.0.11
    volumes:
      - rabbitmq-2-data:/var/lib/rabbitmq
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  # RabbitMQ 节点 3
  rabbitmq-3:
    image: rockylinux:9
    container_name: rabbitmq-3
    hostname: rabbitmq-3
    command: tail -f /dev/null
    networks:
      rabbitmqnet:
        ipv4_address: 172.29.0.12
    volumes:
      - rabbitmq-3-data:/var/lib/rabbitmq
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  # Keepalived 节点 1（主）
  keepalived-1:
    image: rockylinux:9
    container_name: keepalived-1
    hostname: keepalived-1
    command: tail -f /dev/null
    networks:
      rabbitmqnet:
        ipv4_address: 172.29.0.13
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  # Keepalived 节点 2（备）
  keepalived-2:
    image: rockylinux:9
    container_name: keepalived-2
    hostname: keepalived-2
    command: tail -f /dev/null
    networks:
      rabbitmqnet:
        ipv4_address: 172.29.0.14
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

networks:
  rabbitmqnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.0.0/16

volumes:
  rabbitmq-1-data:
  rabbitmq-2-data:
  rabbitmq-3-data: