---
# SonarQube + PostgreSQL 代码审计部署测试（Docker 方式）

services:
  # PostgreSQL 数据库
  postgresql:
    image: postgres:14-alpine
    container_name: postgresql-test
    environment:
      POSTGRES_DB: sonarqube
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarqube_password
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonarqube"]
      interval: 10s
      timeout: 5s
      retries: 5

  # SonarQube 代码质量分析平台
  sonarqube:
    image: sonarqube:10.6.0-community
    container_name: sonarqube-test
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgresql:5432/sonarqube
      SONAR_JDBC_USERNAME: sonarqube
      SONAR_JDBC_PASSWORD: sonarqube_password
      # 限制内存使用（测试环境）
      SONAR_WEB_JVMOPTS: "-Xmx512m -Xms256m"
      SONAR_CE_JVMOPTS: "-Xmx256m -Xms128m"
      SONAR_SEARCH_JVMOPTS: "-Xmx256m -Xms128m"
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-logs:/opt/sonarqube/logs
      - sonarqube-extensions:/opt/sonarqube/extensions
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/system/status"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  postgresql-data:
  sonarqube-data:
  sonarqube-logs:
  sonarqube-extensions: