---
# VictoriaMetrics 集群测试主机清单（Docker 容器）
# 用于在 Docker 容器中测试 Ansible 部署

all:
  children:
    vmcluster:
      hosts:
        vmselect-1:
          ansible_host: 172.20.0.10
          ansible_user: root
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
        vmselect-2:
          ansible_host: 172.20.0.11
          ansible_user: root
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
        vminsert-1:
          ansible_host: 172.20.0.12
          ansible_user: root
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
        vminsert-2:
          ansible_host: 172.20.0.13
          ansible_user: root
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
        vmstorage-1:
          ansible_host: 172.20.0.14
          ansible_user: root
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
        vmstorage-2:
          ansible_host: 172.20.0.15
          ansible_user: root
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
        vmstorage-3:
          ansible_host: 172.20.0.16
          ansible_user: root
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'

    vmselect:
      hosts:
        vmselect-1:
        vmselect-2:

    vminsert:
      hosts:
        vminsert-1:
        vminsert-2:

    vmstorage:
      hosts:
        vmstorage-1:
        vmstorage-2:
        vmstorage-3: