---
# VictoriaMetrics 集群主机清单 (Docker 连接)
all:
  children:
    vmcluster:
      hosts:
        vmselect-1:
          ansible_host: vmselect-1
          ansible_connection: community.docker.docker
          ansible_user: root
          vmselect_port: 8481
        vmselect-2:
          ansible_host: vmselect-2
          ansible_connection: community.docker.docker
          ansible_user: root
          vmselect_port: 8481
        vminsert-1:
          ansible_host: vminsert-1
          ansible_connection: community.docker.docker
          ansible_user: root
          vminsert_port: 8480
        vminsert-2:
          ansible_host: vminsert-2
          ansible_connection: community.docker.docker
          ansible_user: root
          vminsert_port: 8480
        vmstorage-1:
          ansible_host: vmstorage-1
          ansible_connection: community.docker.docker
          ansible_user: root
          vmstorage_port: 8482
        vmstorage-2:
          ansible_host: vmstorage-2
          ansible_connection: community.docker.docker
          ansible_user: root
          vmstorage_port: 8482
        vmstorage-3:
          ansible_host: vmstorage-3
          ansible_connection: community.docker.docker
          ansible_user: root
          vmstorage_port: 8482

    vmselect:
      hosts:
        vmselect-1:
        vmselect-2:

    vminsert:
      hosts:
        vminsert-1:
        vminsert-2:

    vmstorage:
      hosts:
        vmstorage-1:
        vmstorage-2:
        vmstorage-3: