version: '3.8'

# ============================================
# Nginx日志分析系统Rocky测试环境
# ============================================
# 说明：使用Rocky Linux镜像模拟Ansible部署
# 作者：VictoriaMetrics-Full
# 更新时间：2026-01-18
# 内存配置：严格控制每个容器的内存使用
# ============================================

services:
  # ClickHouse数据库
  clickhouse-1:
    image: rockylinux:8
    container_name: clickhouse-1
    hostname: clickhouse-1
    privileged: true
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9004:9004"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
      - clickhouse-logs:/var/log/clickhouse-server
    networks:
      nginx-logs-net:
        ipv4_address: 172.22.0.30
    # 内存限制：2GB
    mem_limit: 2g
    memswap_limit: 2g
    mem_reservation: 1g
    # CPU限制：2核
    cpus: '2'
    command: >
      bash -c "
        # 更新系统
        dnf update -y &&
        # 安装必要软件
        dnf install -y openssh-server sudo vim net-tools wget curl python3 &&
        # 配置SSH
        mkdir -p /var/run/sshd &&
        echo 'root:root' | chpasswd &&
        sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config &&
        sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config &&
        sed -i 's/#UsePAM yes/UsePAM no/' /etc/ssh/sshd_config &&
        # 启动SSH
        /usr/sbin/sshd -D &
        # 保持容器运行
        sleep infinity
      "

  # Vector日志采集
  vector-1:
    image: rockylinux:8
    container_name: vector-1
    hostname: vector-1
    privileged: true
    ports:
      - "8686:8686"
    volumes:
      - vector-data:/etc/vector
      - vector-logs:/var/log/vector
      - nginx-logs:/var/log/nginx:ro
    networks:
      nginx-logs-net:
        ipv4_address: 172.22.0.31
    # 内存限制：512MB
    mem_limit: 512m
    memswap_limit: 512m
    mem_reservation: 256m
    # CPU限制：1核
    cpus: '1'
    command: >
      bash -c "
        # 更新系统
        dnf update -y &&
        # 安装必要软件
        dnf install -y openssh-server sudo vim net-tools wget curl python3 &&
        # 配置SSH
        mkdir -p /var/run/sshd &&
        echo 'root:root' | chpasswd &&
        sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config &&
        sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config &&
        sed -i 's/#UsePAM yes/UsePAM no/' /etc/ssh/sshd_config &&
        # 启动SSH
        /usr/sbin/sshd -D &
        # 保持容器运行
        sleep infinity
      "

  # Nginx服务器
  nginx-1:
    image: rockylinux:8
    container_name: nginx-1
    hostname: nginx-1
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-data:/etc/nginx
      - nginx-logs:/var/log/nginx
    networks:
      nginx-logs-net:
        ipv4_address: 172.22.0.32
    # 内存限制：512MB
    mem_limit: 512m
    memswap_limit: 512m
    mem_reservation: 256m
    # CPU限制：1核
    cpus: '1'
    command: >
      bash -c "
        # 更新系统
        dnf update -y &&
        # 安装必要软件
        dnf install -y openssh-server sudo vim net-tools wget curl python3 nginx &&
        # 配置SSH
        mkdir -p /var/run/sshd &&
        echo 'root:root' | chpasswd &&
        sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config &&
        sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config &&
        sed -i 's/#UsePAM yes/UsePAM no/' /etc/ssh/sshd_config &&
        # 配置Nginx
        mkdir -p /var/log/nginx &&
        echo 'server { listen 80; server_name localhost; location / { return 200 "Hello World"; } access_log /var/log/nginx/access.log; }' > /etc/nginx/conf.d/default.conf &&
        # 启动SSH和Nginx
        /usr/sbin/sshd -D &
        nginx -g 'daemon off;' &
        # 保持容器运行
        sleep infinity
      "

volumes:
  clickhouse-data:
  clickhouse-logs:
  vector-data:
  vector-logs:
  nginx-data:
  nginx-logs:

networks:
  nginx-logs-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/24
          gateway: 172.22.0.1