---
# MySQL Group Replication 集群主机清单（Docker 连接）

all:
  children:
    mysql:
      hosts:
        mysql-mgr-1:
          ansible_host: mysql-mgr-1
          ansible_connection: community.docker.docker
          ansible_user: root
          mysql_server_id: 101
          mgr_local_address: "172.27.0.10:33061"
        mysql-mgr-2:
          ansible_host: mysql-mgr-2
          ansible_connection: community.docker.docker
          ansible_user: root
          mysql_server_id: 102
          mgr_local_address: "172.27.0.11:33061"
        mysql-mgr-3:
          ansible_host: mysql-mgr-3
          ansible_connection: community.docker.docker
          ansible_user: root
          mysql_server_id: 103
          mgr_local_address: "172.27.0.12:33061"
        router-1:
          ansible_host: router-1
          ansible_connection: community.docker.docker
          ansible_user: root

    mgr_cluster:
      hosts:
        mysql-mgr-1:
        mysql-mgr-2:
        mysql-mgr-3:

    router:
      hosts:
        router-1: