---
# Keepalived+Nginx 高可用测试主机清单（Docker 连接）

all:
  children:
    nginx:
      hosts:
        nginx-1:
          ansible_host: nginx-ha-1
          ansible_connection: community.docker.docker
          ansible_user: root
          nginx_port: 80
          nginx_worker_processes: "auto"
        nginx-2:
          ansible_host: nginx-ha-2
          ansible_connection: community.docker.docker
          ansible_user: root
          nginx_port: 80
          nginx_worker_processes: "auto"

    keepalived:
      hosts:
        keepalived-1:
          ansible_host: keepalived-1
          ansible_connection: community.docker.docker
          ansible_user: root
          keepalived_state: MASTER
          keepalived_priority: 100
          keepalived_vip: 172.23.0.100
          keepalived_interface: eth0
        keepalived-2:
          ansible_host: keepalived-2
          ansible_connection: community.docker.docker
          ansible_user: root
          keepalived_state: BACKUP
          keepalived_priority: 90
          keepalived_vip: 172.23.0.100
          keepalived_interface: eth0